collections:
  projectlinks:
    output: false
    permalink: ''
  projects:
    output: true
    permalink: /:collection/:title
  

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"